name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  schedule:
    - cron: "0 0 * * *"

env:
  CFLAGS: -Werror

jobs:
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Install libX11
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends libx11-dev libxext-dev
    - name: Build
      run: make lib all
    - name: Run RISC-V Tests
      run: timeout 600 make lib all test
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        retention-days: 5
        name: rvvm_linux_x86_64
        path: |
          release.linux.x86_64/rvvm_x86_64
          release.linux.x86_64/librvvm.so
          release.linux.x86_64/librvvm_static.a

  win32-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Set up MinGW
      run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends gcc-mingw-w64-x86-64-win32
    - name: Build
      run: make CC=x86_64-w64-mingw32-gcc lib all
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        retention-days: 5
        name: rvvm_win32_x86_64
        path: |
          release.windows.x86_64/rvvm_x86_64.exe
          release.windows.x86_64/librvvm.dll
          release.windows.x86_64/librvvm_static.a

  macos-arm64-build:
    runs-on: macos-latest
    env:
      SDL2_TAR_LINK: https://github.com/libsdl-org/SDL/releases/download/release-2.30.9/SDL2-2.30.9.tar.gz
      SDL2_NAME: SDL2-2.30.9
      CFLAGS: -target arm64-apple-macos11 -Werror -ISDL2-2.30.9/include
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Download SDL2 headers
      run: wget ${{env.SDL2_TAR_LINK}} -O - | tar -xzf - && mv ${{env.SDL2_NAME}}/include src/SDL2
    - name: Build
      run: make lib all
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        retention-days: 5
        name: rvvm_macos_arm64
        path: |
          release.darwin.arm64/rvvm_arm64
          release.darwin.arm64/librvvm.dylib
          release.darwin.arm64/librvvm_static.a

  macos-x86_64-build:
    runs-on: macos-latest
    env:
      SDL2_TAR_LINK: https://github.com/libsdl-org/SDL/releases/download/release-2.30.9/SDL2-2.30.9.tar.gz
      SDL2_NAME: SDL2-2.30.9
      CFLAGS: -target x86_64-apple-macos10.12 -Werror -ISDL2-2.30.9/include
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Download SDL2 headers
      run: wget ${{env.SDL2_TAR_LINK}} -O - | tar -xzf - && mv ${{env.SDL2_NAME}}/include src/SDL2
    - name: Build
      run: make lib all
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        retention-days: 5
        name: rvvm_macos_x86_64
        path: |
          release.darwin.x86_64/rvvm_x86_64
          release.darwin.x86_64/librvvm.dylib
          release.darwin.x86_64/librvvm_static.a
